#! /bin/sh

set -e

gen()
{
    dir="$1"

    (cd "$dir" &&
    cat > CMakeLists.txt <<EOF
install(FILES
    $(ls *.xml)
    DESTINATION \${datadir}/drivers/human/cars/$1
)
EOF
    )
}

for d in *
do
    test -d "$d" && gen "$d"
done
